"""Init

Revision ID: a7a1de84656b
Revises: 
Create Date: 2025-05-12 23:43:15.528634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a1de84656b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='设备ID'),
    sa.Column('name', sa.String(), nullable=False, comment='设备名称'),
    sa.Column('status', sa.Integer(), nullable=False, comment='设备状态: 1-在线, 2-离线, 3-未知'),
    sa.Column('delay', sa.Float(), nullable=True, comment='延迟时间(秒)'),
    sa.Column('last_uptime', sa.DateTime(), nullable=True, comment='最后上线时间'),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True, comment='最后心跳时间'),
    sa.Column('wol_mac', sa.String(), nullable=False, comment='[WOL] MAC地址'),
    sa.Column('wol_host', sa.String(), nullable=True, comment='[WOL] IP地址或域名'),
    sa.Column('wol_port', sa.Integer(), nullable=True, comment='[WOL] 端口号'),
    sa.Column('ssh_host', sa.String(), nullable=False, comment='[SSH] IP地址或域名'),
    sa.Column('ssh_port', sa.Integer(), nullable=False, comment='[SSH] 端口号'),
    sa.Column('ssh_username', sa.String(), nullable=False, comment='[SSH] 账户'),
    sa.Column('ssh_password', sa.String(), nullable=True, comment='[SSH] 密码'),
    sa.Column('ssh_pkey', sa.String(), nullable=True, comment='[SSH] 密钥字符串'),
    sa.Column('ssh_key_filename', sa.String(), nullable=True, comment='[SSH] 密钥文件名'),
    sa.Column('ssh_passphrase', sa.String(), nullable=True, comment='[SSH] 密钥的密码'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device')
    # ### end Alembic commands ###
